// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SILHelloRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SILHelloRoot : GPBRootObject
@end

#pragma mark - SILHelloRequest

typedef GPB_ENUM(SILHelloRequest_FieldNumber) {
  SILHelloRequest_FieldNumber_Id_p = 1,
  SILHelloRequest_FieldNumber_Foo = 2,
  SILHelloRequest_FieldNumber_Bar = 3,
};

@interface SILHelloRequest : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *foo;
/** Test to see if @c foo has been set. */
@property(nonatomic, readwrite) BOOL hasFoo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bar;
/** Test to see if @c bar has been set. */
@property(nonatomic, readwrite) BOOL hasBar;

@end

#pragma mark - SILHelloResponse

typedef GPB_ENUM(SILHelloResponse_FieldNumber) {
  SILHelloResponse_FieldNumber_Id_p = 1,
  SILHelloResponse_FieldNumber_Content = 2,
};

@interface SILHelloResponse : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
