// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.example.hello;

public final class MyHello {
  private MyHello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:helloDemo.HelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 helloId = 1;</code>
     */
    boolean hasHelloId();
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    long getHelloId();

    /**
     * <code>optional string helloContent = 2;</code>
     */
    boolean hasHelloContent();
    /**
     * <code>optional string helloContent = 2;</code>
     */
    java.lang.String getHelloContent();
    /**
     * <code>optional string helloContent = 2;</code>
     */
    com.google.protobuf.ByteString
        getHelloContentBytes();
  }
  /**
   * Protobuf type {@code helloDemo.HelloRequest}
   */
  public static final class HelloRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:helloDemo.HelloRequest)
      HelloRequestOrBuilder {
    // Use HelloRequest.newBuilder() to construct.
    private HelloRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HelloRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HelloRequest defaultInstance;
    public static HelloRequest getDefaultInstance() {
      return defaultInstance;
    }

    public HelloRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HelloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              helloId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              helloContent_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.hello.MyHello.internal_static_helloDemo_HelloRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.hello.MyHello.internal_static_helloDemo_HelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.hello.MyHello.HelloRequest.class, com.example.hello.MyHello.HelloRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<HelloRequest> PARSER =
        new com.google.protobuf.AbstractParser<HelloRequest>() {
      public HelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HelloRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HELLOID_FIELD_NUMBER = 1;
    private long helloId_;
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    public boolean hasHelloId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    public long getHelloId() {
      return helloId_;
    }

    public static final int HELLOCONTENT_FIELD_NUMBER = 2;
    private java.lang.Object helloContent_;
    /**
     * <code>optional string helloContent = 2;</code>
     */
    public boolean hasHelloContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string helloContent = 2;</code>
     */
    public java.lang.String getHelloContent() {
      java.lang.Object ref = helloContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          helloContent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string helloContent = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHelloContentBytes() {
      java.lang.Object ref = helloContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        helloContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      helloId_ = 0L;
      helloContent_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, helloId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getHelloContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, helloId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHelloContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.hello.MyHello.HelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.hello.MyHello.HelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.hello.MyHello.HelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.hello.MyHello.HelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.hello.MyHello.HelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.hello.MyHello.HelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.hello.MyHello.HelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.hello.MyHello.HelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.hello.MyHello.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.hello.MyHello.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.hello.MyHello.HelloRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code helloDemo.HelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:helloDemo.HelloRequest)
        com.example.hello.MyHello.HelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.hello.MyHello.internal_static_helloDemo_HelloRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.hello.MyHello.internal_static_helloDemo_HelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.hello.MyHello.HelloRequest.class, com.example.hello.MyHello.HelloRequest.Builder.class);
      }

      // Construct using com.example.hello.MyHello.HelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        helloId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        helloContent_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.hello.MyHello.internal_static_helloDemo_HelloRequest_descriptor;
      }

      public com.example.hello.MyHello.HelloRequest getDefaultInstanceForType() {
        return com.example.hello.MyHello.HelloRequest.getDefaultInstance();
      }

      public com.example.hello.MyHello.HelloRequest build() {
        com.example.hello.MyHello.HelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.hello.MyHello.HelloRequest buildPartial() {
        com.example.hello.MyHello.HelloRequest result = new com.example.hello.MyHello.HelloRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.helloId_ = helloId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.helloContent_ = helloContent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.hello.MyHello.HelloRequest) {
          return mergeFrom((com.example.hello.MyHello.HelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.hello.MyHello.HelloRequest other) {
        if (other == com.example.hello.MyHello.HelloRequest.getDefaultInstance()) return this;
        if (other.hasHelloId()) {
          setHelloId(other.getHelloId());
        }
        if (other.hasHelloContent()) {
          bitField0_ |= 0x00000002;
          helloContent_ = other.helloContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.hello.MyHello.HelloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.hello.MyHello.HelloRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long helloId_ ;
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public boolean hasHelloId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public long getHelloId() {
        return helloId_;
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public Builder setHelloId(long value) {
        bitField0_ |= 0x00000001;
        helloId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public Builder clearHelloId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        helloId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object helloContent_ = "";
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public boolean hasHelloContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public java.lang.String getHelloContent() {
        java.lang.Object ref = helloContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            helloContent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHelloContentBytes() {
        java.lang.Object ref = helloContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          helloContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public Builder setHelloContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        helloContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public Builder clearHelloContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        helloContent_ = getDefaultInstance().getHelloContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public Builder setHelloContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        helloContent_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:helloDemo.HelloRequest)
    }

    static {
      defaultInstance = new HelloRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:helloDemo.HelloRequest)
  }

  public interface HelloResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:helloDemo.HelloResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 helloId = 1;</code>
     */
    boolean hasHelloId();
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    long getHelloId();

    /**
     * <code>optional string helloContent = 2;</code>
     */
    boolean hasHelloContent();
    /**
     * <code>optional string helloContent = 2;</code>
     */
    java.lang.String getHelloContent();
    /**
     * <code>optional string helloContent = 2;</code>
     */
    com.google.protobuf.ByteString
        getHelloContentBytes();
  }
  /**
   * Protobuf type {@code helloDemo.HelloResponse}
   */
  public static final class HelloResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:helloDemo.HelloResponse)
      HelloResponseOrBuilder {
    // Use HelloResponse.newBuilder() to construct.
    private HelloResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HelloResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HelloResponse defaultInstance;
    public static HelloResponse getDefaultInstance() {
      return defaultInstance;
    }

    public HelloResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HelloResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              helloId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              helloContent_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.hello.MyHello.internal_static_helloDemo_HelloResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.hello.MyHello.internal_static_helloDemo_HelloResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.hello.MyHello.HelloResponse.class, com.example.hello.MyHello.HelloResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<HelloResponse> PARSER =
        new com.google.protobuf.AbstractParser<HelloResponse>() {
      public HelloResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HelloResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HELLOID_FIELD_NUMBER = 1;
    private long helloId_;
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    public boolean hasHelloId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    public long getHelloId() {
      return helloId_;
    }

    public static final int HELLOCONTENT_FIELD_NUMBER = 2;
    private java.lang.Object helloContent_;
    /**
     * <code>optional string helloContent = 2;</code>
     */
    public boolean hasHelloContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string helloContent = 2;</code>
     */
    public java.lang.String getHelloContent() {
      java.lang.Object ref = helloContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          helloContent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string helloContent = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHelloContentBytes() {
      java.lang.Object ref = helloContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        helloContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      helloId_ = 0L;
      helloContent_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, helloId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getHelloContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, helloId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHelloContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.hello.MyHello.HelloResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.hello.MyHello.HelloResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.hello.MyHello.HelloResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.hello.MyHello.HelloResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.hello.MyHello.HelloResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.hello.MyHello.HelloResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.hello.MyHello.HelloResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.hello.MyHello.HelloResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.hello.MyHello.HelloResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.hello.MyHello.HelloResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.hello.MyHello.HelloResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code helloDemo.HelloResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:helloDemo.HelloResponse)
        com.example.hello.MyHello.HelloResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.hello.MyHello.internal_static_helloDemo_HelloResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.hello.MyHello.internal_static_helloDemo_HelloResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.hello.MyHello.HelloResponse.class, com.example.hello.MyHello.HelloResponse.Builder.class);
      }

      // Construct using com.example.hello.MyHello.HelloResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        helloId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        helloContent_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.hello.MyHello.internal_static_helloDemo_HelloResponse_descriptor;
      }

      public com.example.hello.MyHello.HelloResponse getDefaultInstanceForType() {
        return com.example.hello.MyHello.HelloResponse.getDefaultInstance();
      }

      public com.example.hello.MyHello.HelloResponse build() {
        com.example.hello.MyHello.HelloResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.hello.MyHello.HelloResponse buildPartial() {
        com.example.hello.MyHello.HelloResponse result = new com.example.hello.MyHello.HelloResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.helloId_ = helloId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.helloContent_ = helloContent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.hello.MyHello.HelloResponse) {
          return mergeFrom((com.example.hello.MyHello.HelloResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.hello.MyHello.HelloResponse other) {
        if (other == com.example.hello.MyHello.HelloResponse.getDefaultInstance()) return this;
        if (other.hasHelloId()) {
          setHelloId(other.getHelloId());
        }
        if (other.hasHelloContent()) {
          bitField0_ |= 0x00000002;
          helloContent_ = other.helloContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.hello.MyHello.HelloResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.hello.MyHello.HelloResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long helloId_ ;
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public boolean hasHelloId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public long getHelloId() {
        return helloId_;
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public Builder setHelloId(long value) {
        bitField0_ |= 0x00000001;
        helloId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public Builder clearHelloId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        helloId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object helloContent_ = "";
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public boolean hasHelloContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public java.lang.String getHelloContent() {
        java.lang.Object ref = helloContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            helloContent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHelloContentBytes() {
        java.lang.Object ref = helloContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          helloContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public Builder setHelloContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        helloContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public Builder clearHelloContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        helloContent_ = getDefaultInstance().getHelloContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string helloContent = 2;</code>
       */
      public Builder setHelloContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        helloContent_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:helloDemo.HelloResponse)
    }

    static {
      defaultInstance = new HelloResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:helloDemo.HelloResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloDemo_HelloRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_helloDemo_HelloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloDemo_HelloResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_helloDemo_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Hello.proto\022\thelloDemo\"5\n\014HelloRequest" +
      "\022\017\n\007helloId\030\001 \001(\003\022\024\n\014helloContent\030\002 \001(\t\"" +
      "6\n\rHelloResponse\022\017\n\007helloId\030\001 \001(\003\022\024\n\014hel" +
      "loContent\030\002 \001(\tB\034\n\021com.example.helloB\007My" +
      "Hello"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloDemo_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloDemo_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_helloDemo_HelloRequest_descriptor,
        new java.lang.String[] { "HelloId", "HelloContent", });
    internal_static_helloDemo_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloDemo_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_helloDemo_HelloResponse_descriptor,
        new java.lang.String[] { "HelloId", "HelloContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
