// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.example;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface helloOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hello)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 helloId = 1;</code>
     */
    boolean hasHelloId();
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    long getHelloId();

    /**
     * <code>optional string helloName = 2;</code>
     */
    boolean hasHelloName();
    /**
     * <code>optional string helloName = 2;</code>
     */
    java.lang.String getHelloName();
    /**
     * <code>optional string helloName = 2;</code>
     */
    com.google.protobuf.ByteString
        getHelloNameBytes();
  }
  /**
   * Protobuf type {@code hello}
   */
  public static final class hello extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hello)
      helloOrBuilder {
    // Use hello.newBuilder() to construct.
    private hello(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private hello(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final hello defaultInstance;
    public static hello getDefaultInstance() {
      return defaultInstance;
    }

    public hello getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private hello(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              helloId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              helloName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.Hello.internal_static_hello_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.Hello.internal_static_hello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.Hello.hello.class, com.example.Hello.hello.Builder.class);
    }

    public static com.google.protobuf.Parser<hello> PARSER =
        new com.google.protobuf.AbstractParser<hello>() {
      public hello parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new hello(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<hello> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HELLOID_FIELD_NUMBER = 1;
    private long helloId_;
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    public boolean hasHelloId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 helloId = 1;</code>
     */
    public long getHelloId() {
      return helloId_;
    }

    public static final int HELLONAME_FIELD_NUMBER = 2;
    private java.lang.Object helloName_;
    /**
     * <code>optional string helloName = 2;</code>
     */
    public boolean hasHelloName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string helloName = 2;</code>
     */
    public java.lang.String getHelloName() {
      java.lang.Object ref = helloName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          helloName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string helloName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHelloNameBytes() {
      java.lang.Object ref = helloName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        helloName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      helloId_ = 0L;
      helloName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, helloId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getHelloNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, helloId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHelloNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.Hello.hello parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Hello.hello parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Hello.hello parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.Hello.hello parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.Hello.hello parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.Hello.hello parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.Hello.hello parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.Hello.hello parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.Hello.hello parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.Hello.hello parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.Hello.hello prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hello}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hello)
        com.example.Hello.helloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.Hello.internal_static_hello_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.Hello.internal_static_hello_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.Hello.hello.class, com.example.Hello.hello.Builder.class);
      }

      // Construct using com.example.Hello.hello.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        helloId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        helloName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.Hello.internal_static_hello_descriptor;
      }

      public com.example.Hello.hello getDefaultInstanceForType() {
        return com.example.Hello.hello.getDefaultInstance();
      }

      public com.example.Hello.hello build() {
        com.example.Hello.hello result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.Hello.hello buildPartial() {
        com.example.Hello.hello result = new com.example.Hello.hello(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.helloId_ = helloId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.helloName_ = helloName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.Hello.hello) {
          return mergeFrom((com.example.Hello.hello)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.Hello.hello other) {
        if (other == com.example.Hello.hello.getDefaultInstance()) return this;
        if (other.hasHelloId()) {
          setHelloId(other.getHelloId());
        }
        if (other.hasHelloName()) {
          bitField0_ |= 0x00000002;
          helloName_ = other.helloName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.Hello.hello parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.Hello.hello) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long helloId_ ;
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public boolean hasHelloId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public long getHelloId() {
        return helloId_;
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public Builder setHelloId(long value) {
        bitField0_ |= 0x00000001;
        helloId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 helloId = 1;</code>
       */
      public Builder clearHelloId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        helloId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object helloName_ = "";
      /**
       * <code>optional string helloName = 2;</code>
       */
      public boolean hasHelloName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string helloName = 2;</code>
       */
      public java.lang.String getHelloName() {
        java.lang.Object ref = helloName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            helloName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string helloName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHelloNameBytes() {
        java.lang.Object ref = helloName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          helloName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string helloName = 2;</code>
       */
      public Builder setHelloName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        helloName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string helloName = 2;</code>
       */
      public Builder clearHelloName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        helloName_ = getDefaultInstance().getHelloName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string helloName = 2;</code>
       */
      public Builder setHelloNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        helloName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hello)
    }

    static {
      defaultInstance = new hello(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hello)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hello_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\"+\n\005hello\022\017\n\007helloId\030\001 \001(\003\022" +
      "\021\n\thelloName\030\002 \001(\tB\024\n\013com.exampleB\005Hello"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hello_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hello_descriptor,
        new java.lang.String[] { "HelloId", "HelloName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
